### ISSUE TITLE
Linting rules and pre-commit hook for Python linting

### ISSUE THREAD

**Issue by NKeleher** [s3alfisc/pyfixest#296]
Is there a preferred linting configuration? I know that there is a `black` workflow for formatting code with github workflows. 

I'm wondering if there's an interest in using a pre-commit hook for linting. `ruff is the most straightforward implementation of a fast linter that spans a wide variety of linters and formatters (including all of the black formatting rules).

The proposal would be to add a .pre-commit-config.toml with the ruff pre-commit hook.

Then add to the pyproject.toml

At it's simplest add the following accepts the Ruff defaults see [configuration docs](https://docs.astral.sh/ruff/configuration/#configuring-ruff)

```
  # ruff - linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.1.14"
    hooks:
      - id: ruff
        name: ruff
```

At a more complex level, `polars` provides a more complete example of linting rules, including docstyle linting: https://github.com/pola-rs/polars/blob/fd781ebe458fc66fffb73c92d6bb4db629954304/py-polars/pyproject.toml#L124C1-L197C53
